<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    <PackageReference Include="Syncfusion.Blazor" Version="33.2.7" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="33.2.7" />
    <PackageReference Include="Syncfusion.Licensing" Version="33.2.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.UI\BuildingBlocks.UI.csproj" />
  </ItemGroup>

</Project>
